sudo: true
dist: trusty

language: node_js
node_js:
    - "node"

before_script:
    ## build-in chrome
    #- export CHROME_BIN=chromium-browser
    #- export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start

    ## chrome canary
    # - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
    # - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
    # - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
    # - unzip out/chrome-linux.zip -d out
    # - export CHROME_CANARY_BIN=$PWD/out/chrome-linux/chrome
    # - export DISPLAY=:99.0
    # - sh -e /etc/init.d/xvfb start

    ## latest stable chrome
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo dpkg --remove-architecture i386
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
    - export CHROME_BIN=google-chrome-stable

    - git subtree pull -P benchmark/temp/rewriting-new/aexpr-transform-new https://github.com/systemjs/plugin-babel.git master

after_success:
    - bash deploy-to-gh-pages.sh
